import { Station } from '../../prisma/generated';

import { prisma } from '../services/prisma';

export async function seed() {
  try {
    // Evita reseeding se já houver dados
    const count = await prisma.station.count();
    if (count > 0) return;
    const stations: Station[] = [
      {
        id: 1,
        name: 'Posto Petrobras Centro',
        address: 'Av Prof Luiz A.de Oliveira, 366 - Vila Marina',
        lat: -22.0195,
        lng: -47.891,
        rating: 4.5,
        distance: '150m',
        fuels: {
          gasoline: { price: 5.99, updated: 'há 2h' },
          ethanol: { price: 4.29, updated: 'há 2h' },
          diesel: { price: 5.49, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Borracharia', 'Lava-jato'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 2,
        name: 'Shell São Carlos',
        address: 'Rua Conde do Pinhal, 1252 - Centro',
        lat: -22.0245,
        lng: -47.8912,
        rating: 4.3,
        distance: '300m',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.59, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 3,
        name: 'Ipiranga Express',
        address: 'Av São Carlos, 2800 - Jardim Macarengo',
        lat: -22.0178,
        lng: -47.8935,
        rating: 4.7,
        distance: '450m',
        fuels: {
          gasoline: { price: 5.89, updated: 'há 1h' },
          ethanol: { price: 4.19, updated: 'há 1h' },
          diesel: { price: 5.39, updated: 'há 1h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 4,
        name: 'Auto Posto Bandeirantes',
        address: 'Rua Marechal Deodoro, 1520 - Centro',
        lat: -22.0212,
        lng: -47.8856,
        rating: 4.0,
        distance: '600m',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 3h' },
          ethanol: { price: 4.25, updated: 'há 3h' },
          diesel: { price: 5.45, updated: 'há 4h' },
        },
        features: ['Borracharia', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 5,
        name: 'Posto BR Universitário',
        address: 'Rod Washington Luiz, Km 235 - Jardim Guanabara',
        lat: -22.0283,
        lng: -47.9012,
        rating: 4.6,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 5.97, updated: 'há 4h' },
          ethanol: { price: 4.22, updated: 'há 4h' },
          diesel: { price: 5.47, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 6,
        name: 'Rede Graal São Carlos',
        address: 'Rod Washington Luiz, Km 237 - Bairro Planalto',
        lat: -22.0356,
        lng: -47.9102,
        rating: 4.8,
        distance: '2.5km',
        fuels: {
          gasoline: { price: 6.09, updated: 'há 7h' },
          ethanol: { price: 4.39, updated: 'há 7h' },
          diesel: { price: 5.55, updated: 'há 7h' },
        },
        features: [
          'Conveniência',
          'Restaurante',
          'Banheiro',
          'Chuveiro',
          'Hotel',
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 7,
        name: 'Posto Ale Vila Prado',
        address: 'Av Getulio Vargas, 752 - Vila Prado',
        lat: -22.0412,
        lng: -47.8953,
        rating: 3.9,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 8,
        name: 'Auto Posto São Carlos',
        address: 'Rua Dona Alexandrina, 960 - Centro',
        lat: -22.0221,
        lng: -47.8925,
        rating: 4.2,
        distance: '350m',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 5h' },
          ethanol: { price: 4.24, updated: 'há 5h' },
          diesel: { price: 5.42, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 9,
        name: 'Petrobras Vila Nery',
        address: 'Rua 15 de Novembro, 1540 - Vila Nery',
        lat: -22.0169,
        lng: -47.8842,
        rating: 4.4,
        distance: '750m',
        fuels: {
          gasoline: { price: 5.98, updated: 'há 3h' },
          ethanol: { price: 4.28, updated: 'há 3h' },
          diesel: { price: 5.48, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 10,
        name: 'Shell Select Botafogo',
        address: 'Av Dr Carlos Botelho, 1320 - Vila Pureza',
        lat: -22.0189,
        lng: -47.8876,
        rating: 4.5,
        distance: '500m',
        fuels: {
          gasoline: { price: 6.03, updated: 'há 2h' },
          ethanol: { price: 4.33, updated: 'há 2h' },
          diesel: { price: 5.53, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 11,
        name: 'Posto Ipiranga UFSCar',
        address: 'Rod Washington Luiz, Km 233 - Monjolinho',
        lat: -22.0056,
        lng: -47.8932,
        rating: 4.6,
        distance: '2.1km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 12,
        name: 'Auto Posto Cidade Jardim',
        address: 'Av Bruno Ruggiero Filho, 325 - Cidade Jardim',
        lat: -22.0312,
        lng: -47.9045,
        rating: 4.1,
        distance: '1.9km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 8h' },
          ethanol: { price: 4.18, updated: 'há 8h' },
          diesel: { price: 5.41, updated: 'há 8h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 13,
        name: 'Posto BR Santa Felícia',
        address: 'Av Miguel Petroni, 2350 - Santa Felícia',
        lat: -22.0034,
        lng: -47.9076,
        rating: 4.3,
        distance: '2.8km',
        fuels: {
          gasoline: { price: 5.96, updated: 'há 5h' },
          ethanol: { price: 4.26, updated: 'há 5h' },
          diesel: { price: 5.46, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 14,
        name: 'Shell Jardim Medeiros',
        address: 'Av Trabalhador São-carlense, 1750 - Jardim Medeiros',
        lat: -22.0213,
        lng: -47.9002,
        rating: 4.0,
        distance: '1.4km',
        fuels: {
          gasoline: { price: 6.01, updated: 'há 9h' },
          ethanol: { price: 4.31, updated: 'há 9h' },
          diesel: { price: 5.51, updated: 'há 9h' },
        },
        features: ['Conveniência', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 15,
        name: 'Posto Petrobras Redenção',
        address: 'Av Francisco Pereira Lopes, 2850 - Redenção',
        lat: -22.0326,
        lng: -47.8795,
        rating: 4.7,
        distance: '1.5km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 16,
        name: 'Auto Posto Santa Paula',
        address: 'Rua Major Manuel Antônio de Mattos, 1200 - Santa Paula',
        lat: -22.0418,
        lng: -47.9021,
        rating: 3.8,
        distance: '2.2km',
        fuels: {
          gasoline: { price: 5.88, updated: 'há 7h' },
          ethanol: { price: 4.17, updated: 'há 7h' },
          diesel: { price: 5.38, updated: 'há 7h' },
        },
        features: ['Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 17,
        name: 'Posto Ipiranga Bela Vista',
        address: 'Av Bela Cintra, 780 - Bela Vista',
        lat: -22.0265,
        lng: -47.8735,
        rating: 4.4,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 5.91, updated: 'há 4h' },
          ethanol: { price: 4.2, updated: 'há 4h' },
          diesel: { price: 5.4, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 18,
        name: 'Shell Box Santa Marta',
        address: 'Rua José Bonifácio, 950 - Santa Marta',
        lat: -22.0354,
        lng: -47.8823,
        rating: 4.2,
        distance: '1.7km',
        fuels: {
          gasoline: { price: 6.04, updated: 'há 6h' },
          ethanol: { price: 4.34, updated: 'há 6h' },
          diesel: { price: 5.54, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Caixa 24h', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 19,
        name: 'Posto BR Vila Isabel',
        address: 'Av Getúlio Vargas, 560 - Vila Isabel',
        lat: -22.0398,
        lng: -47.8912,
        rating: 3.9,
        distance: '1.6km',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 8h' },
          ethanol: { price: 4.25, updated: 'há 8h' },
          diesel: { price: 5.45, updated: 'há 8h' },
        },
        features: ['Borracharia', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 20,
        name: 'Auto Posto Castelo',
        address: 'Rua São Sebastião, 1870 - Vila Monteiro',
        lat: -22.0187,
        lng: -47.8798,
        rating: 4.3,
        distance: '850m',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 5h' },
          ethanol: { price: 4.23, updated: 'há 5h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 21,
        name: 'Posto Ipiranga Morumbi',
        address: 'Av Morumbi, 3500 - Jardim Morumbi',
        lat: -22.045,
        lng: -47.885,
        rating: 4.6,
        distance: '3.0km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 22,
        name: 'Shell Vila Nery',
        address: 'Rua 13 de Maio, 1200 - Vila Nery',
        lat: -22.018,
        lng: -47.884,
        rating: 4.4,
        distance: '700m',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 3h' },
          ethanol: { price: 4.3, updated: 'há 3h' },
          diesel: { price: 5.5, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 23,
        name: 'Posto BR Planalto',
        address: 'Av João Dario, 450 - Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.1,
        distance: '2.4km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 24,
        name: 'Auto Posto São Carlos 2',
        address: 'Rua São Carlos, 2000 - Jardim São Carlos',
        lat: -22.017,
        lng: -47.895,
        rating: 4.7,
        distance: '500m',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 25,
        name: 'Shell Select São Carlos',
        address: 'Av São Carlos, 1500 - Centro',
        lat: -22.024,
        lng: -47.8915,
        rating: 4.3,
        distance: '300m',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 26,
        name: 'Posto Ipiranga Centro',
        address: 'Rua XV de Novembro, 500 - Centro',
        lat: -22.022,
        lng: -47.891,
        rating: 4.6,
        distance: '200m',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 27,
        name: 'Auto Posto Bandeirantes 2',
        address: 'Av Bandeirantes, 1000 - Jardim Bandeirantes',
        lat: -22.03,
        lng: -47.9,
        rating: 4.2,
        distance: '1.0km',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 3h' },
          ethanol: { price: 4.25, updated: 'há 3h' },
          diesel: { price: 5.45, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 28,
        name: 'Shell Vila Prado',
        address: 'Av Washington Luís, 1500 - Vila Prado',
        lat: -22.041,
        lng: -47.895,
        rating: 4.4,
        distance: '1.5km',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 4h' },
          ethanol: { price: 4.3, updated: 'há 4h' },
          diesel: { price: 5.5, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 29,
        name: 'Posto BR Redenção',
        address: 'Av Redenção, 2500 - Redenção',
        lat: -22.032,
        lng: -47.879,
        rating: 4.7,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 30,
        name: 'Auto Posto Santa Terezinha',
        address: 'Rua Santa Terezinha, 300 - Jardim Santa Terezinha',
        lat: -22.045,
        lng: -47.885,
        rating: 4.1,
        distance: '2.0km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 31,
        name: 'Posto Ipiranga Jardim São Carlos',
        address: 'Av São Carlos, 1800 - Jardim São Carlos',
        lat: -22.018,
        lng: -47.895,
        rating: 4.6,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 32,
        name: 'Shell Select Jardim Planalto',
        address: 'Av Planalto, 1200 - Jardim Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.3,
        distance: '1.0km',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 33,
        name: 'Posto BR Santa Eudóxia',
        address: 'Av Santa Eudóxia, 500 - Santa Eudóxia',
        lat: -22.045,
        lng: -47.87,
        rating: 4.2,
        distance: '2.5km',
        fuels: {
          gasoline: { price: 5.96, updated: 'há 5h' },
          ethanol: { price: 4.26, updated: 'há 5h' },
          diesel: { price: 5.46, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 34,
        name: 'Auto Posto São Carlos 3',
        address: 'Rua São Carlos, 2500 - Jardim São Carlos',
        lat: -22.017,
        lng: -47.895,
        rating: 4.7,
        distance: '600m',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 35,
        name: 'Shell Vila Marina',
        address: 'Av Prof Luiz A.de Oliveira, 1500 - Vila Marina',
        lat: -22.0195,
        lng: -47.891,
        rating: 4.4,
        distance: '300m',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 3h' },
          ethanol: { price: 4.3, updated: 'há 3h' },
          diesel: { price: 5.5, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 36,
        name: 'Posto BR Universitário 2',
        address: 'Rod Washington Luiz, Km 236 - Jardim Guanabara',
        lat: -22.0283,
        lng: -47.9012,
        rating: 4.6,
        distance: '1.1km',
        fuels: {
          gasoline: { price: 5.97, updated: 'há 4h' },
          ethanol: { price: 4.22, updated: 'há 4h' },
          diesel: { price: 5.47, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 37,
        name: 'Rede Graal São Carlos 2',
        address: 'Rod Washington Luiz, Km 238 - Bairro Planalto',
        lat: -22.0356,
        lng: -47.9102,
        rating: 4.8,
        distance: '2.6km',
        fuels: {
          gasoline: { price: 6.09, updated: 'há 7h' },
          ethanol: { price: 4.39, updated: 'há 7h' },
          diesel: { price: 5.55, updated: 'há 7h' },
        },
        features: [
          'Conveniência',
          'Restaurante',
          'Banheiro',
          'Chuveiro',
          'Hotel',
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 38,
        name: 'Posto Ale Vila Prado 2',
        address: 'Av Getulio Vargas, 800 - Vila Prado',
        lat: -22.0412,
        lng: -47.8953,
        rating: 3.9,
        distance: '1.9km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 39,
        name: 'Auto Posto São Carlos 4',
        address: 'Rua Dona Alexandrina, 1100 - Centro',
        lat: -22.0221,
        lng: -47.8925,
        rating: 4.2,
        distance: '400m',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 5h' },
          ethanol: { price: 4.24, updated: 'há 5h' },
          diesel: { price: 5.42, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 40,
        name: 'Petrobras Vila Nery 2',
        address: 'Rua 15 de Novembro, 1600 - Vila Nery',
        lat: -22.0169,
        lng: -47.8842,
        rating: 4.4,
        distance: '800m',
        fuels: {
          gasoline: { price: 5.98, updated: 'há 3h' },
          ethanol: { price: 4.28, updated: 'há 3h' },
          diesel: { price: 5.48, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 41,
        name: 'Shell Select Botafogo 2',
        address: 'Av Dr Carlos Botelho, 1400 - Vila Pureza',
        lat: -22.0189,
        lng: -47.8876,
        rating: 4.5,
        distance: '550m',
        fuels: {
          gasoline: { price: 6.03, updated: 'há 2h' },
          ethanol: { price: 4.33, updated: 'há 2h' },
          diesel: { price: 5.53, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 42,
        name: 'Posto Ipiranga UFSCar 2',
        address: 'Rod Washington Luiz, Km 234 - Monjolinho',
        lat: -22.0056,
        lng: -47.8932,
        rating: 4.6,
        distance: '2.2km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 43,
        name: 'Auto Posto Cidade Jardim 2',
        address: 'Av Bruno Ruggiero Filho, 350 - Cidade Jardim',
        lat: -22.0312,
        lng: -47.9045,
        rating: 4.1,
        distance: '2.0km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 8h' },
          ethanol: { price: 4.18, updated: 'há 8h' },
          diesel: { price: 5.41, updated: 'há 8h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 44,
        name: 'Posto BR Santa Felícia 2',
        address: 'Av Miguel Petroni, 2400 - Santa Felícia',
        lat: -22.0034,
        lng: -47.9076,
        rating: 4.3,
        distance: '3.0km',
        fuels: {
          gasoline: { price: 5.96, updated: 'há 5h' },
          ethanol: { price: 4.26, updated: 'há 5h' },
          diesel: { price: 5.46, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 45,
        name: 'Shell Jardim Medeiros 2',
        address: 'Av Trabalhador São-carlense, 1800 - Jardim Medeiros',
        lat: -22.0213,
        lng: -47.9002,
        rating: 4.0,
        distance: '1.6km',
        fuels: {
          gasoline: { price: 6.01, updated: 'há 9h' },
          ethanol: { price: 4.31, updated: 'há 9h' },
          diesel: { price: 5.51, updated: 'há 9h' },
        },
        features: ['Conveniência', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 46,
        name: 'Posto Petrobras Redenção 2',
        address: 'Av Francisco Pereira Lopes, 2900 - Redenção',
        lat: -22.0326,
        lng: -47.8795,
        rating: 4.7,
        distance: '1.7km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 47,
        name: 'Auto Posto Santa Paula 2',
        address: 'Rua Major Manuel Antônio de Mattos, 1300 - Santa Paula',
        lat: -22.0418,
        lng: -47.9021,
        rating: 3.8,
        distance: '2.3km',
        fuels: {
          gasoline: { price: 5.88, updated: 'há 7h' },
          ethanol: { price: 4.17, updated: 'há 7h' },
          diesel: { price: 5.38, updated: 'há 7h' },
        },
        features: ['Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 48,
        name: 'Posto Ipiranga Bela Vista 2',
        address: 'Av Bela Cintra, 800 - Bela Vista',
        lat: -22.0265,
        lng: -47.8735,
        rating: 4.4,
        distance: '1.3km',
        fuels: {
          gasoline: { price: 5.91, updated: 'há 4h' },
          ethanol: { price: 4.2, updated: 'há 4h' },
          diesel: { price: 5.4, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 49,
        name: 'Shell Box Santa Marta 2',
        address: 'Rua José Bonifácio, 1000 - Santa Marta',
        lat: -22.0354,
        lng: -47.8823,
        rating: 4.2,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 6.04, updated: 'há 6h' },
          ethanol: { price: 4.34, updated: 'há 6h' },
          diesel: { price: 5.54, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Caixa 24h', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 50,
        name: 'Posto BR Vila Isabel 2',
        address: 'Av Getúlio Vargas, 600 - Vila Isabel',
        lat: -22.0398,
        lng: -47.8912,
        rating: 3.9,
        distance: '1.7km',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 8h' },
          ethanol: { price: 4.25, updated: 'há 8h' },
          diesel: { price: 5.45, updated: 'há 8h' },
        },
        features: ['Borracharia', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 51,
        name: 'Auto Posto Castelo 2',
        address: 'Rua São Sebastião, 1900 - Vila Monteiro',
        lat: -22.0187,
        lng: -47.8798,
        rating: 4.3,
        distance: '900m',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 5h' },
          ethanol: { price: 4.23, updated: 'há 5h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 52,
        name: 'Posto Ipiranga Morumbi 2',
        address: 'Av Morumbi, 3600 - Jardim Morumbi',
        lat: -22.045,
        lng: -47.885,
        rating: 4.6,
        distance: '3.1km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 53,
        name: 'Shell Vila Nery 2',
        address: 'Rua 13 de Maio, 1300 - Vila Nery',
        lat: -22.018,
        lng: -47.884,
        rating: 4.4,
        distance: '750m',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 3h' },
          ethanol: { price: 4.3, updated: 'há 3h' },
          diesel: { price: 5.5, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 54,
        name: 'Posto BR Planalto 2',
        address: 'Av João Dario, 500 - Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.1,
        distance: '2.5km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 55,
        name: 'Auto Posto São Carlos 5',
        address: 'Rua São Carlos, 3000 - Jardim São Carlos',
        lat: -22.017,
        lng: -47.895,
        rating: 4.7,
        distance: '700m',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 56,
        name: 'Shell Select São Carlos 2',
        address: 'Av São Carlos, 2000 - Centro',
        lat: -22.024,
        lng: -47.8915,
        rating: 4.3,
        distance: '350m',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 57,
        name: 'Posto Ipiranga Centro 2',
        address: 'Rua XV de Novembro, 600 - Centro',
        lat: -22.022,
        lng: -47.891,
        rating: 4.6,
        distance: '250m',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 58,
        name: 'Auto Posto Bandeirantes 3',
        address: 'Av Bandeirantes, 1200 - Jardim Bandeirantes',
        lat: -22.03,
        lng: -47.9,
        rating: 4.2,
        distance: '1.1km',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 3h' },
          ethanol: { price: 4.25, updated: 'há 3h' },
          diesel: { price: 5.45, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 59,
        name: 'Shell Vila Prado 2',
        address: 'Av Washington Luís, 2000 - Vila Prado',
        lat: -22.041,
        lng: -47.895,
        rating: 4.4,
        distance: '1.6km',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 4h' },
          ethanol: { price: 4.3, updated: 'há 4h' },
          diesel: { price: 5.5, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 60,
        name: 'Posto BR Redenção 3',
        address: 'Av Redenção, 3000 - Redenção',
        lat: -22.032,
        lng: -47.879,
        rating: 4.7,
        distance: '1.9km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 61,
        name: 'Auto Posto Santa Terezinha 2',
        address: 'Rua Santa Terezinha, 400 - Jardim Santa Terezinha',
        lat: -22.045,
        lng: -47.885,
        rating: 4.1,
        distance: '2.1km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 62,
        name: 'Posto Ipiranga Jardim São Carlos 2',
        address: 'Av São Carlos, 2000 - Jardim São Carlos',
        lat: -22.018,
        lng: -47.895,
        rating: 4.6,
        distance: '1.3km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 63,
        name: 'Shell Select Jardim Planalto 2',
        address: 'Av Planalto, 1300 - Jardim Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.3,
        distance: '1.1km',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 64,
        name: 'Posto BR Santa Eudóxia 2',
        address: 'Av Santa Eudóxia, 600 - Santa Eudóxia',
        lat: -22.045,
        lng: -47.87,
        rating: 4.2,
        distance: '2.6km',
        fuels: {
          gasoline: { price: 5.96, updated: 'há 5h' },
          ethanol: { price: 4.26, updated: 'há 5h' },
          diesel: { price: 5.46, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 65,
        name: 'Auto Posto São Carlos 6',
        address: 'Rua São Carlos, 3500 - Jardim São Carlos',
        lat: -22.017,
        lng: -47.895,
        rating: 4.7,
        distance: '800m',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 66,
        name: 'Shell Vila Marina 2',
        address: 'Av Prof Luiz A.de Oliveira, 2000 - Vila Marina',
        lat: -22.0195,
        lng: -47.891,
        rating: 4.4,
        distance: '350m',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 3h' },
          ethanol: { price: 4.3, updated: 'há 3h' },
          diesel: { price: 5.5, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 67,
        name: 'Posto BR Universitário 3',
        address: 'Rod Washington Luiz, Km 237 - Jardim Guanabara',
        lat: -22.0283,
        lng: -47.9012,
        rating: 4.6,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 5.97, updated: 'há 4h' },
          ethanol: { price: 4.22, updated: 'há 4h' },
          diesel: { price: 5.47, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 68,
        name: 'Rede Graal São Carlos 3',
        address: 'Rod Washington Luiz, Km 239 - Bairro Planalto',
        lat: -22.0356,
        lng: -47.9102,
        rating: 4.8,
        distance: '2.7km',
        fuels: {
          gasoline: { price: 6.09, updated: 'há 7h' },
          ethanol: { price: 4.39, updated: 'há 7h' },
          diesel: { price: 5.55, updated: 'há 7h' },
        },
        features: [
          'Conveniência',
          'Restaurante',
          'Banheiro',
          'Chuveiro',
          'Hotel',
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 69,
        name: 'Posto Ale Vila Prado 3',
        address: 'Av Getulio Vargas, 900 - Vila Prado',
        lat: -22.0412,
        lng: -47.8953,
        rating: 3.9,
        distance: '2.0km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 70,
        name: 'Auto Posto São Carlos 7',
        address: 'Rua Dona Alexandrina, 1200 - Centro',
        lat: -22.0221,
        lng: -47.8925,
        rating: 4.2,
        distance: '450m',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 5h' },
          ethanol: { price: 4.24, updated: 'há 5h' },
          diesel: { price: 5.42, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 71,
        name: 'Petrobras Vila Nery 3',
        address: 'Rua 15 de Novembro, 1700 - Vila Nery',
        lat: -22.0169,
        lng: -47.8842,
        rating: 4.4,
        distance: '900m',
        fuels: {
          gasoline: { price: 5.98, updated: 'há 3h' },
          ethanol: { price: 4.28, updated: 'há 3h' },
          diesel: { price: 5.48, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 72,
        name: 'Shell Select Botafogo 3',
        address: 'Av Dr Carlos Botelho, 1500 - Vila Pureza',
        lat: -22.0189,
        lng: -47.8876,
        rating: 4.5,
        distance: '600m',
        fuels: {
          gasoline: { price: 6.03, updated: 'há 2h' },
          ethanol: { price: 4.33, updated: 'há 2h' },
          diesel: { price: 5.53, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 73,
        name: 'Posto Ipiranga UFSCar 3',
        address: 'Rod Washington Luiz, Km 235 - Monjolinho',
        lat: -22.0056,
        lng: -47.8932,
        rating: 4.6,
        distance: '2.3km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 74,
        name: 'Auto Posto Cidade Jardim 3',
        address: 'Av Bruno Ruggiero Filho, 400 - Cidade Jardim',
        lat: -22.0312,
        lng: -47.9045,
        rating: 4.1,
        distance: '2.1km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 8h' },
          ethanol: { price: 4.18, updated: 'há 8h' },
          diesel: { price: 5.41, updated: 'há 8h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 75,
        name: 'Posto BR Santa Felícia 3',
        address: 'Av Miguel Petroni, 2500 - Santa Felícia',
        lat: -22.0034,
        lng: -47.9076,
        rating: 4.3,
        distance: '3.1km',
        fuels: {
          gasoline: { price: 5.96, updated: 'há 5h' },
          ethanol: { price: 4.26, updated: 'há 5h' },
          diesel: { price: 5.46, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 76,
        name: 'Shell Jardim Medeiros 3',
        address: 'Av Trabalhador São-carlense, 1900 - Jardim Medeiros',
        lat: -22.0213,
        lng: -47.9002,
        rating: 4.0,
        distance: '1.7km',
        fuels: {
          gasoline: { price: 6.01, updated: 'há 9h' },
          ethanol: { price: 4.31, updated: 'há 9h' },
          diesel: { price: 5.51, updated: 'há 9h' },
        },
        features: ['Conveniência', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 77,
        name: 'Posto Petrobras Redenção 3',
        address: 'Av Francisco Pereira Lopes, 2950 - Redenção',
        lat: -22.0326,
        lng: -47.8795,
        rating: 4.7,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 78,
        name: 'Auto Posto Santa Paula 3',
        address: 'Rua Major Manuel Antônio de Mattos, 1400 - Santa Paula',
        lat: -22.0418,
        lng: -47.9021,
        rating: 3.8,
        distance: '2.4km',
        fuels: {
          gasoline: { price: 5.88, updated: 'há 7h' },
          ethanol: { price: 4.17, updated: 'há 7h' },
          diesel: { price: 5.38, updated: 'há 7h' },
        },
        features: ['Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 79,
        name: 'Posto Ipiranga Bela Vista 3',
        address: 'Av Bela Cintra, 900 - Bela Vista',
        lat: -22.0265,
        lng: -47.8735,
        rating: 4.4,
        distance: '1.4km',
        fuels: {
          gasoline: { price: 5.91, updated: 'há 4h' },
          ethanol: { price: 4.2, updated: 'há 4h' },
          diesel: { price: 5.4, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 80,
        name: 'Shell Box Santa Marta 3',
        address: 'Rua José Bonifácio, 1100 - Santa Marta',
        lat: -22.0354,
        lng: -47.8823,
        rating: 4.2,
        distance: '1.9km',
        fuels: {
          gasoline: { price: 6.04, updated: 'há 6h' },
          ethanol: { price: 4.34, updated: 'há 6h' },
          diesel: { price: 5.54, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Caixa 24h', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 81,
        name: 'Posto BR Vila Isabel 3',
        address: 'Av Getúlio Vargas, 640 - Vila Isabel',
        lat: -22.0398,
        lng: -47.8912,
        rating: 3.9,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 5.95, updated: 'há 8h' },
          ethanol: { price: 4.25, updated: 'há 8h' },
          diesel: { price: 5.45, updated: 'há 8h' },
        },
        features: ['Borracharia', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 82,
        name: 'Auto Posto Castelo 3',
        address: 'Rua São Sebastião, 2000 - Vila Monteiro',
        lat: -22.0187,
        lng: -47.8798,
        rating: 4.3,
        distance: '950m',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 5h' },
          ethanol: { price: 4.23, updated: 'há 5h' },
          diesel: { price: 5.43, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 83,
        name: 'Posto Ipiranga Morumbi 3',
        address: 'Av Morumbi, 3700 - Jardim Morumbi',
        lat: -22.045,
        lng: -47.885,
        rating: 4.6,
        distance: '3.2km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 84,
        name: 'Shell Vila Nery 3',
        address: 'Rua 13 de Maio, 1400 - Vila Nery',
        lat: -22.018,
        lng: -47.884,
        rating: 4.4,
        distance: '800m',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 3h' },
          ethanol: { price: 4.3, updated: 'há 3h' },
          diesel: { price: 5.5, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 85,
        name: 'Posto BR Planalto 3',
        address: 'Av João Dario, 600 - Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.1,
        distance: '2.6km',
        fuels: {
          gasoline: { price: 5.85, updated: 'há 6h' },
          ethanol: { price: 4.15, updated: 'há 6h' },
          diesel: { price: 5.35, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 86,
        name: 'Auto Posto São Carlos 8',
        address: 'Rua São Carlos, 4000 - Jardim São Carlos',
        lat: -22.017,
        lng: -47.895,
        rating: 4.7,
        distance: '900m',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 87,
        name: 'Shell Select São Carlos 3',
        address: 'Av São Carlos, 2500 - Centro',
        lat: -22.024,
        lng: -47.8915,
        rating: 4.3,
        distance: '400m',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 88,
        name: 'Posto Ipiranga Centro 3',
        address: 'Rua XV de Novembro, 700 - Centro',
        lat: -22.022,
        lng: -47.891,
        rating: 4.6,
        distance: '300m',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 89,
        name: 'Auto Posto Bandeirantes 4',
        address: 'Av Bandeirantes, 1400 - Jardim Bandeirantes',
        lat: -22.03,
        lng: -47.9,
        rating: 4.2,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 5.93, updated: 'há 3h' },
          ethanol: { price: 4.25, updated: 'há 3h' },
          diesel: { price: 5.45, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 90,
        name: 'Shell Vila Prado 3',
        address: 'Av Washington Luís, 2500 - Vila Prado',
        lat: -22.041,
        lng: -47.895,
        rating: 4.4,
        distance: '1.7km',
        fuels: {
          gasoline: { price: 6.0, updated: 'há 4h' },
          ethanol: { price: 4.3, updated: 'há 4h' },
          diesel: { price: 5.5, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 91,
        name: 'Posto BR Redenção 4',
        address: 'Av Redenção, 3500 - Redenção',
        lat: -22.032,
        lng: -47.879,
        rating: 4.7,
        distance: '2.0km',
        fuels: {
          gasoline: { price: 5.94, updated: 'há 3h' },
          ethanol: { price: 4.24, updated: 'há 3h' },
          diesel: { price: 5.44, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 92,
        name: 'Auto Posto Santa Terezinha 3',
        address: 'Rua Santa Terezinha, 500 - Jardim Santa Terezinha',
        lat: -22.045,
        lng: -47.885,
        rating: 4.1,
        distance: '2.2km',
        fuels: {
          gasoline: { price: 5.9, updated: 'há 2h' },
          ethanol: { price: 4.2, updated: 'há 2h' },
          diesel: { price: 5.4, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 93,
        name: 'Posto Ipiranga Jardim São Carlos 3',
        address: 'Av São Carlos, 2200 - Jardim São Carlos',
        lat: -22.018,
        lng: -47.895,
        rating: 4.6,
        distance: '1.4km',
        fuels: {
          gasoline: { price: 5.92, updated: 'há 4h' },
          ethanol: { price: 4.21, updated: 'há 4h' },
          diesel: { price: 5.43, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 94,
        name: 'Shell Select Jardim Planalto 3',
        address: 'Av Planalto, 1400 - Jardim Planalto',
        lat: -22.036,
        lng: -47.91,
        rating: 4.3,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 6.05, updated: 'há 5h' },
          ethanol: { price: 4.35, updated: 'há 5h' },
          diesel: { price: 5.55, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 95,
        name: 'Posto Ipiranga Paulista',
        address: 'Av. Paulista, 1500 - Bela Vista, São Paulo',
        lat: -23.5629,
        lng: -46.6544,
        rating: 4.5,
        distance: '200m',
        fuels: {
          gasoline: { price: 6.29, updated: 'há 3h' },
          ethanol: { price: 4.59, updated: 'há 3h' },
          diesel: { price: 5.79, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h', 'Lava-jato'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 96,
        name: 'Shell Select Pinheiros',
        address: 'Rua dos Pinheiros, 950 - Pinheiros, São Paulo',
        lat: -23.5661,
        lng: -46.6911,
        rating: 4.7,
        distance: '350m',
        fuels: {
          gasoline: { price: 6.35, updated: 'há 2h' },
          ethanol: { price: 4.65, updated: 'há 2h' },
          diesel: { price: 5.85, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 97,
        name: 'Petrobras Vila Mariana',
        address: 'Rua Domingos de Morais, 2500 - Vila Mariana, São Paulo',
        lat: -23.5877,
        lng: -46.6382,
        rating: 4.3,
        distance: '500m',
        fuels: {
          gasoline: { price: 6.25, updated: 'há 4h' },
          ethanol: { price: 4.55, updated: 'há 4h' },
          diesel: { price: 5.75, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Borracharia', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 98,
        name: 'Auto Posto Moema',
        address: 'Av. Ibirapuera, 1800 - Moema, São Paulo',
        lat: -23.6006,
        lng: -46.6618,
        rating: 4.6,
        distance: '700m',
        fuels: {
          gasoline: { price: 6.32, updated: 'há 1h' },
          ethanol: { price: 4.62, updated: 'há 1h' },
          diesel: { price: 5.82, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Caixa 24h', 'Restaurante'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 99,
        name: 'Posto BR Faria Lima',
        address: 'Av. Brigadeiro Faria Lima, 3500 - Itaim Bibi, São Paulo',
        lat: -23.5868,
        lng: -46.6835,
        rating: 4.8,
        distance: '450m',
        fuels: {
          gasoline: { price: 6.39, updated: 'há 2h' },
          ethanol: { price: 4.69, updated: 'há 2h' },
          diesel: { price: 5.89, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 100,
        name: 'Posto Ipiranga Morumbi',
        address: 'Av. Giovanni Gronchi, 5400 - Morumbi, São Paulo',
        lat: -23.6088,
        lng: -46.7221,
        rating: 4.4,
        distance: '1.2km',
        fuels: {
          gasoline: { price: 6.27, updated: 'há 5h' },
          ethanol: { price: 4.57, updated: 'há 5h' },
          diesel: { price: 5.77, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 101,
        name: 'Shell Jardins',
        address: 'Rua Estados Unidos, 1200 - Jardins, São Paulo',
        lat: -23.5706,
        lng: -46.661,
        rating: 4.7,
        distance: '600m',
        fuels: {
          gasoline: { price: 6.36, updated: 'há 3h' },
          ethanol: { price: 4.66, updated: 'há 3h' },
          diesel: { price: 5.86, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Caixa 24h', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 102,
        name: 'Auto Posto Brooklin',
        address:
          'Av. Engenheiro Luís Carlos Berrini, 1500 - Brooklin, São Paulo',
        lat: -23.607,
        lng: -46.6936,
        rating: 4.5,
        distance: '800m',
        fuels: {
          gasoline: { price: 6.3, updated: 'há 4h' },
          ethanol: { price: 4.6, updated: 'há 4h' },
          diesel: { price: 5.8, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 103,
        name: 'Posto Petrobras Avenida Brasil',
        address: 'Av. Brasil, 1800 - Jardim América, São Paulo',
        lat: -23.5745,
        lng: -46.6737,
        rating: 4.3,
        distance: '550m',
        fuels: {
          gasoline: { price: 6.28, updated: 'há 6h' },
          ethanol: { price: 4.58, updated: 'há 6h' },
          diesel: { price: 5.78, updated: 'há 6h' },
        },
        features: ['Conveniência', 'Troca de Óleo', 'Calibragem'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 104,
        name: 'Shell Select Vila Olímpia',
        address: 'Rua Funchal, 500 - Vila Olímpia, São Paulo',
        lat: -23.5953,
        lng: -46.6869,
        rating: 4.6,
        distance: '650m',
        fuels: {
          gasoline: { price: 6.37, updated: 'há 2h' },
          ethanol: { price: 4.67, updated: 'há 2h' },
          diesel: { price: 5.87, updated: 'há 2h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 105,
        name: 'Posto Ipiranga Santana',
        address: 'Av. Cruzeiro do Sul, 3500 - Santana, São Paulo',
        lat: -23.5025,
        lng: -46.6252,
        rating: 4.2,
        distance: '1.5km',
        fuels: {
          gasoline: { price: 6.24, updated: 'há 5h' },
          ethanol: { price: 4.54, updated: 'há 5h' },
          diesel: { price: 5.74, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 106,
        name: 'Auto Posto Tatuapé',
        address: 'Rua Tuiuti, 2500 - Tatuapé, São Paulo',
        lat: -23.5367,
        lng: -46.5719,
        rating: 4.4,
        distance: '1.8km',
        fuels: {
          gasoline: { price: 6.26, updated: 'há 7h' },
          ethanol: { price: 4.56, updated: 'há 7h' },
          diesel: { price: 5.76, updated: 'há 7h' },
        },
        features: ['Conveniência', 'Lava-jato', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 107,
        name: 'Posto BR Lapa',
        address: 'Rua Clélia, 1800 - Lapa, São Paulo',
        lat: -23.5292,
        lng: -46.7012,
        rating: 4.3,
        distance: '2.0km',
        fuels: {
          gasoline: { price: 6.29, updated: 'há 4h' },
          ethanol: { price: 4.59, updated: 'há 4h' },
          diesel: { price: 5.79, updated: 'há 4h' },
        },
        features: ['Conveniência', 'Calibragem', 'Caixa 24h'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 108,
        name: 'Shell Select Cidade Jardim',
        address: 'Av. Cidade Jardim, 1000 - Jardim Europa, São Paulo',
        lat: -23.5785,
        lng: -46.6856,
        rating: 4.8,
        distance: '700m',
        fuels: {
          gasoline: { price: 6.38, updated: 'há 1h' },
          ethanol: { price: 4.68, updated: 'há 1h' },
          diesel: { price: 5.88, updated: 'há 1h' },
        },
        features: [
          'Conveniência',
          'Lava-jato',
          'Troca de Óleo',
          'Calibragem',
          'Caixa 24h',
        ],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 109,
        name: 'Posto Petrobras Higienópolis',
        address: 'Rua Piauí, 700 - Higienópolis, São Paulo',
        lat: -23.5418,
        lng: -46.6558,
        rating: 4.5,
        distance: '450m',
        fuels: {
          gasoline: { price: 6.31, updated: 'há 3h' },
          ethanol: { price: 4.61, updated: 'há 3h' },
          diesel: { price: 5.81, updated: 'há 3h' },
        },
        features: ['Conveniência', 'Calibragem', 'Troca de Óleo'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        id: 110,
        name: 'Auto Posto Liberdade',
        address: 'Rua Vergueiro, 1500 - Liberdade, São Paulo',
        lat: -23.5698,
        lng: -46.6378,
        rating: 4.2,
        distance: '600m',
        fuels: {
          gasoline: { price: 6.27, updated: 'há 5h' },
          ethanol: { price: 4.57, updated: 'há 5h' },
          diesel: { price: 5.77, updated: 'há 5h' },
        },
        features: ['Conveniência', 'Calibragem', 'Borracharia'],
        createdAt: new Date(),
        updatedAt: new Date(),
      },
    ];

    await prisma.station.createMany({
      data: stations.map((s: any) => s),
    });
  } catch (error) {
    console.error('Error seeding database:', error);
  }
}
